name: brass
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  audio_service: ^0.18.18
  audio_service_mpris: ^0.2.0
  bech32: ^0.2.2
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  get: ^4.7.2
  media_kit: ^1.2.1
  media_kit_libs_video: ^1.0.7
  media_kit_video: ^1.3.1
  ndk: ^0.5.1
  ndk_rust_verifier: ^0.4.1
  nip19: ^0.2.0
  nostr_widgets: ^1.1.0
  path: ^1.9.1
  path_provider: ^2.1.5
  sembast: ^3.8.5+1
  sembast_cache_manager: ^1.0.3
  sembast_web: ^2.4.2
  system_theme: ^3.1.2
  toastification: ^3.0.3
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
